PhotographyWebAppCore/Components/HeaderMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PhotographyWebAppCore.Models;
using PhotographyWebAppCore.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotographyWebAppCore.Components
{
    public class HeaderMenuViewComponent: ViewComponent
    {
        private readonly ICategoryRepository _categoryRepository;
        public HeaderMenuViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<PhotoCategory> categories = await _categoryRepository.GetAll();
            return View(categories);
        }
    }
}

PhotographyWebAppCore/Components/SliderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using PhotographyWebAppCore.Models;
using PhotographyWebAppCore.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotographyWebAppCore.Controllers
{
    public class SliderViewComponent : ViewComponent
    {

        private AppConfig _appConfig;
        private readonly IAlbumRepository _albumRepository;

        public SliderViewComponent(IOptionsMonitor<AppConfig> appConfig, IAlbumRepository albumRepository)
        {
            //读取appsetting.json文件中的配置信息，并当数据修改后允许热重载
            _appConfig = appConfig.CurrentValue;
            appConfig.OnChange(config=>
            {
                _appConfig = config;
            });


            _albumRepository = albumRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //读取appsettings中储存的幻灯片相册id
            List<int> sliderAlbumIds = _appConfig.SliderAlbumIds;
            List<Album> albums = await _albumRepository.GetAll();
            //如果没有设置，返回所有相册。如果设置了，则返回指定的相册。
            if (sliderAlbumIds != null)
            {
                albums = albums.Where(x => sliderAlbumIds.Contains(x.Id)).ToList();
            }
            return View(albums);
        }
    }
}

PhotographyWebAppCore/Controllers/PhotoCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using PhotographyWebAppCore.Models;
using PhotographyWebAppCore.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotographyWebAppCore.Controllers
{
    public class PhotoCategoryController : Controller
    {
        private readonly IAlbumRepository _albumRepository;
        private readonly ICategoryRepository _categoryRepository;
        public PhotoCategoryController(IAlbumRepository albumRepository,ICategoryRepository categoryRepository)
        {
            _albumRepository = albumRepository;
            _categoryRepository = categoryRepository;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        [HttpGet]
        public async Task<IActionResult> Index(int categoryId)
        {
            PhotoCategory category = await _categoryRepository.GetById(categoryId);
            ViewBag.Category = category;

            List<Album> albums = await _albumRepository.GetAll();
            albums = albums.Where(x => x.CategoryId == categoryId).ToList();
            return View(albums);
        }
    }
}

PhotographyWebAppCore/Views/Shared/Components/HeaderMenu/Default.cshtml
@model List<PhotoCategory>; 

<div class="collapse navbar-collapse textal" id="navbarNav">
    <ul class="navbar-nav mx-auto">
        <li class="nav-item active">
            <a class="nav-link" asp-controller="Home" asp-action="Index">主页</a>
        </li>
        @*<li class="nav-item">
                <a class="nav-link" href="#">经典案例</a>
            </li>*@
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                经典案例
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                @if (Model != null && Model.Count != 0)
                {
                    @foreach (PhotoCategory category in Model)
                    {
                        <a class="dropdown-item" asp-controller="PhotoCategory" asp-action="Index" asp-route-categoryId="@category.Id">@category.Name</a>
                    }
                }

                @*<a class="dropdown-item" asp-controller="PhotoCategory" asp-action="Index">人像写真</a>
                <a class="dropdown-item" href="#">婚纱摄影</a>
                <a class="dropdown-item" href="#">婚礼记录</a>
                <a class="dropdown-item" href="#">儿童摄影</a>
                <a class="dropdown-item" href="#">亲子照</a>
                <a class="dropdown-item" href="#">活动跟拍</a>*@
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">优惠套餐</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">在线服务</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">走进摄影师</a>
        </li>
    </ul>
</div>