PhotographyWebAppCore/Components/HeaderMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PhotographyWebAppCore.Models;
using PhotographyWebAppCore.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotographyWebAppCore.Components
{
    public class HeaderMenuViewComponent: ViewComponent
    {
        private readonly ICategoryRepository _categoryRepository;
        public HeaderMenuViewComponent(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<PhotoCategory> categories = await _categoryRepository.GetAll();
            return View(categories);
        }
    }
}

PhotographyWebAppCore/Controllers/AdminAlbumController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PhotographyWebAppCore.Models;
using PhotographyWebAppCore.Repositories;
using PhotographyWebAppCore.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotographyWebAppCore.Controllers
{
    public class AdminAlbumController : Controller
    {
        private readonly IAlbumRepository _albumRepository;
        private readonly ICategoryRepository _categoryRepository;
        public AdminAlbumController(IAlbumRepository albumRepository, ICategoryRepository categoryRepository)
        {
            _albumRepository = albumRepository;
            _categoryRepository = categoryRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string categoryId = null)
        {
            List<Album> albums = await _albumRepository.GetAll();
            ViewBag.AllAlbumCount = (albums == null) ? 0 : albums.Count();
            //按照类型分组
            List<AlbumViewCategoryViewModel> categoryViewModelList = new List<AlbumViewCategoryViewModel>();
            var categoryGroups = albums.GroupBy(x => x.CategoryId).OrderBy(x => x.Key);
            foreach (var group in categoryGroups)
            {
                if (group.Key == null)
                {
                    categoryViewModelList.Add(new AlbumViewCategoryViewModel
                    {
                        CategoryId = "null",
                        CategoryName = "未指定",
                        AlbumCount = group.Count(),
                    });
                }
                else
                {
                    PhotoCategory category = await _categoryRepository.GetById((int)group.Key);
                    categoryViewModelList.Add(new AlbumViewCategoryViewModel
                    {
                        CategoryId = group.Key.ToString(),
                        CategoryName = category.Name,
                        AlbumCount = group.Count(),
                    });
                }
            }
            ViewBag.CategoryViewModel = categoryViewModelList;
            //接收传入的参数【类型】
            if (categoryId != null)
            {
                if (categoryId == "null")
                {
                    albums = albums.Where(x => x.CategoryId == null).ToList();
                }
                else
                {
                    int id = Int32.Parse(categoryId);
                    albums = albums.Where(x => x.CategoryId == id).ToList();
                }
            }

            return View(albums);
        }
        [HttpGet]
        public async Task<IActionResult> CreateOne(string albumName = null, bool isSuccess = false, int? albumId = null)
        {
            //ViewBag.IsSuccess = isSuccess;
            List<PhotoCategory> categories = await _categoryRepository.GetAll();
            //下拉选择菜单
            //第一个参数是要传入的列表，第二个参数是作为value提交的字段，第三个参数是作为text显示的字段。
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            ViewBag.IsSuccess = isSuccess;
            ViewBag.AlbumName = albumName;
            ViewBag.AlbumId = albumId;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateOne(Album album)
        {
            if (ModelState.IsValid)
            {
                Album a = await _albumRepository.CreateOne(album);
                return RedirectToAction(nameof(CreateOne), new { isSuccess = true, albumName = a.Title, albumId = a.Id });
            }
            else
            {
                List<PhotoCategory> categories = await _categoryRepository.GetAll();
                ViewBag.Categories = new SelectList(categories, "Id", "Name");
                return View();
            }
        }
        [HttpPost]
        public async Task<IActionResult> DeleteById(int id)
        {
            await _albumRepository.DeleteById_LeavePhotos(id);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> DeleteByIdAndPhotos(int id)
        {
            await _albumRepository.DeleteById_DeletePhotos(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            Album album = await _albumRepository.GetById(id);
            PhotoCategory category = album.Category;
            List<PhotoCategory> categories = await _categoryRepository.GetAll();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", category);
            return View(album);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Album album)
        {
            await _albumRepository.UpdateOne(album);
            return RedirectToAction(nameof(Index));
        }
    }
}

PhotographyWebAppCore/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using PhotographyWebAppCore.Models;
using PhotographyWebAppCore.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PhotographyWebAppCore.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAccountRepository _accountRepository;
   
        public AdminController(IAccountRepository accountRepository)
        {
            _accountRepository = accountRepository;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(Administrator model)
        {
            if (ModelState.IsValid)
            {
                Microsoft.AspNetCore.Identity.SignInResult result = await _accountRepository.SignInAsync(model);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "用户名或密码错误");
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _accountRepository.SignOutAsync();
            return RedirectToAction("Login");
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        
    }
}

PhotographyWebAppCore/Controllers/AdminPhotoController.cs
using Microsoft.AspNetCore.Mvc;
using PhotographyWebAppCore.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PhotographyWebAppCore.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using PhotographyWebAppCore.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using PhotographyWebAppCore.ViewModels;

namespace PhotographyWebAppCore.Controllers
{
    public class AdminPhotoController : Controller
    {
        private readonly IPhotoRepository _photoRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IAlbumRepository _albumRepository;
        private readonly IPhotographerRepository _photographerRepository;

        public AdminPhotoController(IPhotoRepository photoRepository,
            IWebHostEnvironment webHostEnvironment,
            IAlbumRepository albumRepository,
            IPhotographerRepository photographerRepository)
        {
            _photoRepository = photoRepository;
            _webHostEnvironment = webHostEnvironment;
            _albumRepository = albumRepository;
            _photographerRepository = photographerRepository;
        }
        public async Task<IActionResult> Index(string albumId = null,string photographerId=null,string date = null)
        {
            List<Photo> photos = await _photoRepository.GetAll();
            //按照相册分组
            var albumGroups = photos.GroupBy(x => x.AlbumId).OrderBy(x=>x.Key);
            List<PhotoViewAlbumViewModel> albumViewModelList = new List<PhotoViewAlbumViewModel>();
            foreach (var group in albumGroups)
            {
                if (group.Key == null)
                {
                    albumViewModelList.Add(new PhotoViewAlbumViewModel
                    {
                        AlbumId = "null",
                        AlbumName = "未指定",
                        AlbumPhotoCount = group.Count(),
                    });
                }
                else
                {
                    Album album = await _albumRepository.GetById((int)group.Key);
                    albumViewModelList.Add(new PhotoViewAlbumViewModel
                    {

                        AlbumId = group.Key.ToString(),
                        AlbumName = album.Title,
                        AlbumPhotoCount = group.Count(),
                    });
                }
            }
            //按照摄影师分组
            var photographerGroups = photos.GroupBy(x => x.PhotographerId).OrderBy(x => x.Key);
            List<PhotoViewPhotographerViewModel> photographerViewModelList = new List<PhotoViewPhotographerViewModel>();
            foreach(var group in photographerGroups)
            {
                if (group.Key == null)
                {
                    photographerViewModelList.Add(new PhotoViewPhotographerViewModel
                    {
                        PhotographerId = "null",
                        PhotographerName = "未指定",
                        PhotographerPhotoCount = group.Count(),
                    });
                }
                else
                {
                    Photographer photographer = await _photographerRepository.GetById((int)group.Key);
                    photographerViewModelList.Add(new PhotoViewPhotographerViewModel
                    {
                        PhotographerId = group.Key.ToString(),
                        PhotographerName = photographer.Name,
                        PhotographerPhotoCount = group.Count(),
                    });
                }
            }
            //按照日期分组
            var dateGroups = photos.GroupBy(x => x.UploadDateTime.Date);
            Dictionary<string, int> dateDic = new Dictionary<string, int>();
            foreach (var group in dateGroups)
            {
                dateDic.Add(group.Key.Date.ToString("yyyy'-'MM'-'dd"), group.Count());
            }


            //使用ViewBag传递
            ViewBag.AlbumViewModel = albumViewModelList;
            ViewBag.PhotographerViewModel = photographerViewModelList;
            ViewBag.DateDic = dateDic;
            ViewBag.AllPhotoCount = photos.Count();

            //接收传入的参数【相册】
            if (albumId != null)
            {
                if (albumId == "null")
                {
                    photos = photos.Where(x => x.AlbumId == null).ToList();
                }
                else
                {
                    int id = Int32.Parse(albumId);
                    photos = photos.Where(x => x.AlbumId == id).ToList();
                }
            }
            //接收传入的参数【摄影师】
            if (photographerId != null)
            {
                if (photographerId == "null")
                {
                    photos = photos.Where(x => x.PhotographerId == null).ToList();
                }
                else
                {
                    int id = Int32.Parse(photographerId);
                    photos = photos.Where(x => x.PhotographerId == id).ToList();
                }
            }
            //接收传入的参数【日期】
            if (date != null)
            {
                DateTime d=DateTime.Parse(date);
                photos = photos.Where(x => x.UploadDateTime.Date == d).ToList();
            }

            return View(photos);
        }
        [HttpGet]
        public async Task<IActionResult> AddPhotos(int? albumId = null,int? photographerId=null)
        {
            List<Album> albums = await _albumRepository.GetAll();
            List<Photographer> photographers = await _photographerRepository.GetAll();

            Album selectedAlbum = null;
            if (albumId != null)
            {
                selectedAlbum = albums.FirstOrDefault(x => x.Id == albumId);
            }
            Photographer selectedpPhotographer = null;
            if (photographerId != null)
            {
                selectedpPhotographer = photographers.FirstOrDefault(x => x.Id == photographerId);
            }
            //添加照片的时候选择摄影师
            ViewBag.Photographers=new SelectList(photographers, "Id", "Name", selectedpPhotographer);
            //添加照片的时候选择相册
            ViewBag.Albums = new SelectList(albums, "Id", "Title", selectedAlbum);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddPhotos(PhotoUploadViewModel viewModel)
        {
            List<IFormFile> files = viewModel.Files;
            //int albumId = viewModel.AlbumId;

            if (ModelState.IsValid && files.Count > 0)
            {
                List<Photo> photos = new List<Photo>();
                foreach (IFormFile file in files)
                {
                    Photo photo = new Photo
                    {
                        PhotoFile = file,
                    };
                    if (viewModel.AlbumId != null)
                    {
                        photo.AlbumId = viewModel.AlbumId;
                    }
                    if (viewModel.PhotographerId != null)
                    {
                        photo.PhotographerId = viewModel.PhotographerId;
                    }
                    photos.Add(photo);
                    await SavePhoto(photo);
                    photo.ResizeImageAndSaveCopies();
                }
                List<Photo> ps = await _photoRepository.CreateMultiple(photos);
                List<int> ids = ps.Select(x => x.Id).ToList();
                return RedirectToAction(nameof(EditAfterUpload), new { ids });
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id, bool isSuccess = false)
        {
            Photo photo = await _photoRepository.GetById(id);
            List<Album> albums = await _albumRepository.GetAll();
            List<Photographer> photographers = await _photographerRepository.GetAll();
            ViewBag.Albums = new SelectList(albums, "Id", "Title");
            ViewBag.Photographers = new SelectList(photographers, "Id", "Name");
            ViewBag.IsSuccess = isSuccess;
            return View(photo);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Photo photo)
        {
            Photo p = await _photoRepository.UpdateOne(photo);
            return RedirectToAction(nameof(Update), new { id = p.Id, isSuccess = true });
        }

        //[HttpGet]
        //public IActionResult AddOnePhoto()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public async Task<IActionResult> AddOnePhoto(Photo photo)
        //{
        //    if (ModelState.IsValid && photo.PhotoFile != null)
        //    {
        //        //把照片储存到本地文件夹
        //        await SavePhoto(photo);
        //        //调整图片大小，并储存到对应的文件夹中
        //        photo.ResizeImageAndSaveCopies();
        //        //提交到数据库
        //        await _photoRepository.CreateOne(photo);
        //        return View(photo);
        //    }
        //    else
        //    {
        //        return View();
        //    }

        //}
        [HttpPost]
        public async Task<IActionResult> DeleteOneById(int id)
        {
            //删除本地文件夹内的照片文件
            Photo photo = await _photoRepository.GetById(id);
            string rootFolder = _webHostEnvironment.WebRootPath;
            System.IO.File.Delete(Path.Combine(rootFolder, photo.Path_Origional));
            System.IO.File.Delete(Path.Combine(rootFolder, photo.Path_Big));
            System.IO.File.Delete(Path.Combine(rootFolder, photo.Path_Middle));
            System.IO.File.Delete(Path.Combine(rootFolder, photo.Path_Small));
            //去数据库中删除文件记录
            await _photoRepository.DeleteById(id);
            return RedirectToAction(nameof(Index));
        }

        //把照片储存到本地文件夹
        private async Task SavePhoto(Photo photo)
        {

PhotographyWebAppCore/Views/Shared/_Layout.cshtml
@*@addTagHelper*, PhotographyWebAppCore*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PhotographyWebAppCore</title>
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bricklayer/bricklayer.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="fixed-header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <a href="#">
                <img src="~/images/logo.png" alt="logo" class="navbar-logo" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <vc:header-menu></vc:header-menu>
        </nav>
    </header>
    @*<div class="container">
        <main role="main" class="pb-3">*@
    @RenderBody()


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GuoGuo Photography Studio- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bricklayer/bricklayer.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PhotographyWebAppCore/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Administrator</title>
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bricklayer/bricklayer.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="fixed-header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top ">
            <a href="#">
                <img src="~/images/logo.png" alt="logo" class="navbar-logo" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Admin" asp-action="Index">后台主页</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            内容管理
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" asp-controller="AdminPhoto" asp-action="Index">照片</a>
                            <a class="dropdown-item" asp-controller="AdminAlbum" asp-action="Index">相册</a>
                            <a class="dropdown-item" asp-controller="AdminCategory" asp-action="Index">类型</a>
                            <a class="dropdown-item" asp-controller="AdminPhotographer" asp-action="Index">摄影师</a>
                        </div>
                    </li>
                    @*<li class="nav-item">
                            <a class="nav-link" href="#">优惠套餐</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">在线服务</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">走进摄影师</a>
                        </li>*@
                </ul>
                <a class="btn btn-outline-danger my-2 my-sm-0" asp-controller="Admin" asp-action="Logout">退出</a>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bricklayer/bricklayer.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts",required:false)
</body>
</html>